"""empty message

Revision ID: 03ca9abe9e8b
Revises: e2d16f43a578
Create Date: 2019-09-27 11:52:48.569678

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '03ca9abe9e8b'
down_revision = 'e2d16f43a578'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leavemsgs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=512), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leavemsgs_timestamp'), 'leavemsgs', ['timestamp'], unique=False)
    op.add_column('articles', sa.Column('add_time', sa.DateTime(), nullable=True))
    op.add_column('articles', sa.Column('filename', sa.String(length=64), nullable=True))
    op.add_column('articles', sa.Column('html_path', sa.String(length=128), nullable=True))
    op.add_column('articles', sa.Column('markdown_path', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_articles_add_time'), 'articles', ['add_time'], unique=False)
    op.drop_index('ix_articles_timestamp', table_name='articles')
    op.drop_column('articles', 'body')
    op.drop_column('articles', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('timestamp', mysql.DATETIME(), nullable=True))
    op.add_column('articles', sa.Column('body', mysql.TEXT(), nullable=True))
    op.create_index('ix_articles_timestamp', 'articles', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_articles_add_time'), table_name='articles')
    op.drop_column('articles', 'markdown_path')
    op.drop_column('articles', 'html_path')
    op.drop_column('articles', 'filename')
    op.drop_column('articles', 'add_time')
    op.drop_index(op.f('ix_leavemsgs_timestamp'), table_name='leavemsgs')
    op.drop_table('leavemsgs')
    # ### end Alembic commands ###
