"""empty message

Revision ID: 0d161a8b35c2
Revises: 03ca9abe9e8b
Create Date: 2019-09-27 12:35:14.847783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d161a8b35c2'
down_revision = '03ca9abe9e8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('posted', sa.Boolean(), nullable=True))
    op.add_column('articles', sa.Column('posted_time', sa.DateTime(), nullable=True))
    op.add_column('articles', sa.Column('verified', sa.Boolean(), nullable=True))
    op.add_column('articles', sa.Column('verified_time', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_articles_posted_time'), 'articles', ['posted_time'], unique=False)
    op.create_index(op.f('ix_articles_verified_time'), 'articles', ['verified_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articles_verified_time'), table_name='articles')
    op.drop_index(op.f('ix_articles_posted_time'), table_name='articles')
    op.drop_column('articles', 'verified_time')
    op.drop_column('articles', 'verified')
    op.drop_column('articles', 'posted_time')
    op.drop_column('articles', 'posted')
    # ### end Alembic commands ###
