"""empty message

Revision ID: 564fbdbff39a
Revises: 9912ea5fc23c
Create Date: 2019-09-26 15:35:33.680626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '564fbdbff39a'
down_revision = '9912ea5fc23c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    op.add_column('articles', sa.Column('body', sa.Text(), nullable=True))
    op.add_column('articles', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_articles_timestamp'), 'articles', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articles_timestamp'), table_name='articles')
    op.drop_column('articles', 'timestamp')
    op.drop_column('articles', 'body')
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
