"""empty message

Revision ID: a98bb4de0220
Revises: 0d161a8b35c2
Create Date: 2019-09-27 13:56:41.833588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a98bb4de0220'
down_revision = '0d161a8b35c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('url', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'url')
    # ### end Alembic commands ###
